### ISSUE TITLE
Packets out of order...

### ISSUE THREAD

**Issue by proseLA** [CcMarc/AbuseIPDB#5]
i am now starting to see error logs like this:
```
#5 abuseipdb_observer->checkAbusiveIP() called at [/includes/classes/observers/class.abuseipdb_observer.php:20]
#6 abuseipdb_observer->update() called at [/includes/classes/class.base.php:118]
#7 base->notify() called at [/includes/templates/myTemplate/common/html_header.php:19]
#8 require(/includes/templates/myTemplate/common/html_header.php) called at [/index.php:42]
--> PHP Warning: Packets out of order. Expected 1 received 0. Packet size=145 in /includes/classes/db/mysql/query_factory.php on line 415.
```
have you come across it before?  i wonder if nothing is coming back from the abuse database.

**Comment by CcMarc** [comment]
This error usually occurs due to a network issue between your PHP application and MySQL server, or because of a misconfiguration in your MySQL server. I am not sure it is related to abuseipdb module.

Here are a few steps you can take to diagnose and resolve the issue:

Check your MySQL server configuration: Ensure that your MySQL server is properly configured. You might need to adjust some parameters related to networking, packet size, etc.

Check Network Issues: If your MySQL server is hosted on a different machine than your web server, there could be network issues that are causing this error. Check for any network latency, instability, or packet loss.

Increase Max Allowed Packet Size: The 'max_allowed_packet' parameter in your MySQL server configuration file defines the maximum size of a sendable packet. If this value is smaller than the packet you're trying to send, it will cause this error. You can try to increase this value and see if it resolves the error.

**Comment by proseLA** [comment]
ok.  thanks.
